version: "3"

networks:
  nginx-proxy:
    external: true

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    image: web_alfin:dev
    container_name: alfin_dev
    command: python -m flask run --host 0.0.0.0 --port 5000
    restart: always
    env_file:
      - ./.env
    networks: 
        - nginx-proxy
    volumes:
      - ./:/app
    ports:
      - "5000:5000"

