version: "3"

networks:
  nginx-proxy:
    external: true

services:
  web:
    build: 
      context: ../
      dockerfile: ./docker/Dockerfile.dev
    image: web_alfin:dev
    container_name: alfin_dev
    command: python -m  flask run --host 0.0.0.0 --port 5000
    # command: python -m  flask run --host 0.0.0.0 --port 5000  debugpy --listen 0.0.0.0:5001
    restart: always
    env_file:
      - ../.env
    networks: 
        - nginx-proxy
    volumes:
      - ../:/app
    ports:
      - "5000:5000"
      - "5001:5001"

