version: "3"

networks:
  nginx-proxy:
    external: true

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    image: web_alfin:latest
    container_name: alfin
    command: bash -c "bash ./boot.sh; sleep 1"
    restart: always
    env_file:
      - ./.env
    networks: 
        - nginx-proxy
    volumes:
      - ./:/app
    ports:
      - "5000:5000"
      - "80:5000"



