FROM python:3.9-slim

WORKDIR /app

COPY ./Pipfile ./Pipfile.lock ./
RUN apt-get update \
 && apt-get install unixodbc -y \
 && apt-get install unixodbc-dev -y \
 && apt-get install freetds-dev -y \
 && apt-get install freetds-bin -y \
 && apt-get install tdsodbc -y \
 && apt-get install --reinstall build-essential -y \
 && apt-get install -y build-essential libpq-dev libxml2 libxml2-dev libxslt1.1 libxslt1-dev libffi-dev libz-dev \
 && pip install -U pip && pip install pipenv && pipenv install --system --dev --ignore-pipfile
RUN pwd
COPY ./docker/odbc.ini /etc
COPY ./docker/odbcinst.ini /etc
COPY ./docker/freetds.conf /etc/freetds
RUN chmod 644 /etc/odbc.ini
RUN chmod 644 /etc/odbcinst.ini
RUN chmod 644 /etc/freetds/freetds.conf

EXPOSE 5000
